#!/bin/bash
mkdir -p ../data/csvs ../data/zips
cd ../data

# seq -f "%02g" creates 01, 02, ... 12
for j in $(seq -f "%02g" 1 12); do
  FILE="2024${j}-citibike-tripdata.zip"
  wget "https://s3.amazonaws.com/tripdata/$FILE"
done

# Extract and Clean
unzip "*.zip" -d ./csvs
mv *.zip ./zips/
cd ./csvs
sed -i 's/rideable_type/is_electric/g; s/classic_bike/0/g; s/electric_bike/1/g; s/member_casual/is_m/g; s/member/1/g; s/casual/0/g' *.csv