#!/bin/sh
#making directory
mkdir ../data
cd ../data
#downloading data
for j in {01..12}; do 
  wget https://s3.amazonaws.com/tripdata/2024$j-citibike-tripdata.zip
done
# unzipping
unzip "*.zip"
# creating directory and moving csvs
mkdir ./csvs
mv "*.csv" ./csvs 
# creating zips and moving zips
mkdir ./zips && mv *.zip ./zips
# changing directory for transformation 
cd ./csvs
#cleaning data
sed -i 's/rideable_type/is_electric/; s/classic_bike/0/; s/electric_bike/1/; s/member_casual/is_m/; s/member/1/; s/casual/0/' *.csv